import { Language } from ".";

const frCH: Language = {
    name: "fr-CH",
    nativeName: "français",
    definition: {
        hello: "Bonjour !",
        home: "Accueil",
        epherome: "Epherome",
        accounts: "Comptes",
        profiles: "Profils",
        settings: "Paramètres",
        launch: "Lancer",
        launching: "Lancement en cours",
        edit: "Modifier",
        news: "Actualités",
        create: "Créer",
        cancel: "Annuler",
        remove: "Supprimer",
        fine: "Bien",
        email: "Email",
        password: "Mot de passe",
        username: "Nom d'utilisateur",
        authserver: "Serveur d'authentification",
        name: "Nom",
        directory: "Répertoire",
        version: "Version",
        general: "Général",
        appearance: "Apparence",
        about: "À propos",
        os: "Système d'exploitation",
        language: "Langue",
        save: "Enregistrer",
        warning: "Avertissement",
        done: "Terminé",
        add: "Ajouter",
        tip: "Astuce",
        help: "Aide",
        refresh: "Actualiser",
        collapse: "Réduire",
        expand: "Développer",
        useDefault: "<Par défaut>",
        haveNot: "N/A",
        export: "Exporter",
        "account.mojang": "Compte Mojang",
        "account.microsoft": "Compte Microsoft",
        "account.authlib": "Injecteur Authlib",
        "account.offline": "Compte hors ligne",
        "account.errCreating": "Informations incorrectes ou serveur d'authentification hors ligne.",
        "account.removing": "Suppression du compte",
        "account.notSelected": "Aucun compte sélectionné",
        "account.wrongPassword": "Mot de passe incorrect",
        "account.inputPassword": "Veuillez entrer le mot de passe",
        "account.msAccNoMinecraft": "Votre compte Microsoft ne contient pas Minecraft",
        "account.clickToLogin": "Cliquez sur « Créer » pour vous connecter à votre compte Microsoft.",
        "account.skin": "Skin",
        "account.skin.notSupportedExcludeMojangMs": "La visualisation des skins n'est prise en charge que pour les comptes Mojang ou Microsoft.",
        "profile.removing": "Suppression du profil",
        "profile.notSelected": "Aucun profil de jeu sélectionné",
        "profile.openDirectory": "Ouvrir le répertoire",
        "profile.usuallyDotMinecraftEtc": "Sur Windows, il s'agit généralement de 「.minecraft」, tandis que sur macOS et Linux, il s'agit généralement de 「minecraft」.",
        "profile.maps": "Cartes",
        "profile.resourcePacks": "Packs de ressources",
        "profile.resolution": "Résolution",
        "profile.jvmArgs": "Arguments JVM",
        "profile.noContent": "Aucun contenu",
        "profile.disable": "Désactiver",
        "profile.enable": "Activer",
        "profile.import": "Importer",
        "profile.gameDirIsolation": "Isolation du répertoire de jeu",
        "profile.gameDirIsolation.description": "Utilisez des répertoires de jeu distincts pour les versions différentes.",
        "profile.showEpherome": "Afficher Epherome",
        "profile.showEpherome.description": "Affiche l'icône Epherome dans le coin inférieur gauche de la page d'accueil de Minecraft.",
        "profile.install": "Installer",
        "profile.installing": "Installation en cours",
        "profile.installForMinecraft": "Installer pour Minecraft {0}",
        "profile.selectInstallContent": "Veuillez sélectionner le contenu à installer.",
        "profile.installerAdaptToSomething": "{1} adapté à Minecraft {0}",
        "profile.noInstallerAdaptToSomething": "Aucun installateur disponible pour Minecraft {0} et {1}",
        "profile.canOnlyInstallOnVanilla": "L'installation n'est possible qu'avec Minecraft Vanilla.",
        "profile.safeLog4j": "Log4J sécurisé",
        "profile.safeLog4j.description": "Activez 'formatMsgNoLookups' pour prévenir les problèmes de Log4J.",
        "profile.exportModpack": "Exporter le pack de mods",
        "profile.gameOptionsPath": "Chemin des options de jeu",
        "profile.resourceType.resourcePack": "Pack de ressources",
        "profile.resourceType.shaderPack": "Pack de shaders",
        "settings.epheromePath": "Chemin d'Epherome",
        "settings.officialSite": "Site officiel",
        "settings.openSourceSoftware": "Logiciels open source",
        "settings.downloadProvider": "Fournisseur de téléchargement",
        "settings.downloadProvider.official": "Officiel",
        "settings.downloadConcurrency": "Concurrence des téléchargements",
        "settings.hitokoto": "Hitokoto",
        "settings.languageHelper": "Seule la traduction en anglais est complète. Les autres traductions sont fournies par des bénévoles bienveillants.",
        "settings.theme": "Thème",
        "settings.theme.followOS": "Suivre le système d'exploitation",
        "settings.titleBar": "Barre de titre",
        "settings.titleBar.message": "Redémarrez Epherome pour appliquer les paramètres de la barre de titre.",
        "settings.devMode": "Mode développeur",
        "settings.downloadProvider.description": "Si la source officielle est lente, vous pouvez essayer de la remplacer.",
        "settings.downloadCurrency.description": "Nombre maximum de fichiers pouvant être téléchargés simultanément.",
        "settings.showNews": "Afficher les actualités",
        "settings.autoCheckUpdate": "Vérification automatique des mises à jour",
        "display": "Affichage",
        "java.executablePath": "Chemin du fichier exécutable Java",
        "java.manage": "Gérer Java",
        "java.invalidPath": "Chemin non valide",
        "java.duplicatePath": "Chemin en double",
        "java.detect": "Détection automatique",
        "java.bitNumber": "{0} bits",
        "java.default": "Java par défaut",
        "java.installJava": "Installer Java",
        "java.pleaseGoTo": "Pour installer cette version de JDK, veuillez cliquer sur le lien ci-dessous.",
        "java.nickName": "Nom JVM",
        "download": "Télécharger",
        "downloading": "Téléchargement en cours",
        "downloadingSomething": "Téléchargement de {0} en cours",
        "download.profileName": "Nom du profil",
        "download.preparing": "Préparation en cours",
        "download.notSelected": "Aucune version sélectionnée",
        "version.release": "Version officielle",
        "version.snapshot": "Version snapshot",
        "version.old": "Ancienne version",
        "version.old_alpha": "Ancienne version (Alpha)",
        "version.old_beta": "Ancienne version (Beta)",
        "processes": "Processus",
        "processes.noMinecraft": "Aucun processus Minecraft",
        "processes.logExported": "Le journal a été exporté à l'emplacement suivant :\n{0}",
        "processes.terminate": "Forcer la fermeture",
        "processes.terminateIrreversible": "La terminaison forcée d'un processus peut entraîner la perte de certaines données importantes. Voulez-vous continuer ?",
        "processes.lookupLog": "Consulter le journal",
        "processes.exportLog": "Exporter le journal",
        "processes.lookupProfile": "Consulter la configuration du jeu",
        "processes.notSelected": "Aucun processus sélectionné",
        "extensions": "Extensions",
        "epheromeUpdate": "Mise à jour d'Epherome",
        "epheromeUpdate.check": "Vérifier les mises à jour",
        "epheromeUpdate.available": "Nouvelle version {0} disponible maintenant.",
        "epheromeUpdate.availableMessage": "Veuillez vous rendre sur le site officiel d'Epherome pour télécharger la dernière version.",
        "epheromeUpdate.needNot": "Epherome est déjà à jour.",
        "launching.noAccOrProSelected": "Aucun compte ou configuration de jeu sélectionné.",
        "launching.considerUsingJava17": "À partir de Minecraft 1.18, le démarrage de Minecraft nécessite Java 17.",
        "launching.considerUsingJava16": "À partir de Minecraft 1.17, le démarrage de Minecraft nécessite Java 16.",
        "launching.considerUsingJava8": "Avant Minecraft 1.6, le démarrage de Minecraft nécessite Java 8.",
        "launching.javaNotFound": "Java introuvable",
        "launching.javaNotFoundMessage": "Java n'a pas été trouvé sur votre ordinateur. Veuillez l'installer et l'ajouter dans les paramètres.",
        "launching.downloadingAsset": "Téléchargement des fichiers de ressources en cours",
        "launching.downloadingLib": "Téléchargement des fichiers de bibliothèque en cours",
        "launching.crashReport": "Minecraft a planté !",
        "launching.crashReport.helper": "Consultez la page de gestion des processus pour plus de détails.",
        "ext.apps": "Applications",
        "theme.create": "Créer un thème...",
        "theme.newTheme": "Nouveau thème",
        "theme.type": "Type",
        "theme.light": "Thème clair",
        "theme.dark": "Thème sombre",
        "theme.background": "Couleur d'arrière-plan",
        "theme.secondary": "Couleur secondaire",
        "theme.divider": "Couleur de séparation",
        "theme.contrast": "Couleur du texte",
        "theme.primary": "Couleur principale",
        "theme.shallow": "Couleur du texte en surface",
        "theme.card": "Couleur de la carte",
        "theme.danger": "Couleur d'avertissement",
        "task.manager": "Gestionnaire de tâches",
        "task.noTasks": "Aucune tâche en cours",
        "modpack.import": "Importer un pack de mods",
        "modpack.filePath": "Chemin du fichier du pack de mods (*.zip)",
        "modpack.unzipping": "Décompression en cours",
        "modpack.installingMinecraft": "Installation de Minecraft en cours",
        "modpack.installingModLoader": "Installation du chargeur de mods en cours",
        "modpack.info": "Informations sur le pack de mods",
        "modpack.name": "Nom du pack de mods",
        "modpack.version": "Version du pack de mods",
        "modpack.author": "Auteur du modpack",
        "modpack.selectFiles": "Sélectionner des fichiers",
        "modpack.export": "Exporter",
        "modpack.exporting": "Exportation en cours",
        next: "Suivant",
        previous: "Précédent",
        search: "Recherche",
        internetNotAvailable: "Web différent grâce à vous, impossible de se connecter à Internet.",
        errorOccurred: "Une erreur s'est produite",
        notSupportedYet: "Désolé, cette fonctionnalité n'est pas encore prise en charge.",
        confirmRemoving: "Voulez-vous vraiment le supprimer ? Cette action est irréversible.",
        continueAnyway: "Continuer quand même",
        moveToTrash: "Déplacer vers la corbeille",
        confirmMoveSomethingToTrash: "Voulez-vous vraiment déplacer {0} vers la corbeille ? Cette action est irréversible.",
        exportedAt: "Exporté ici :",
        versionOfSomething: "Version {0}",
        doneMessage: "La tâche est terminée.",
        minimize: "Réduire",
        quit: "Quitter",
        confirmQuitting: "Voulez-vous vraiment quitter Epherome ?",
        removeFilesAsWell: "Supprimer les fichiers également",
        unableToRefreshMsToken: "Impossible de rafraîchir le jeton de compte Microsoft. Veuillez vous reconnecter.",
        msLoginAgain: "Se reconnecter",
        ephPersonalCenter: "Centre personnel",
        ephLogin: "Se connecter",
        "ext.installed": "Installé",
        "ext.recommended": "Recommandé",
        "ext.all": "Tous",
        "ext.noItems": "Aucun élément",
        "ext.remove": "Supprimer de Epherome",
        "ext.add": "Ajouter à Epherome",
        "ext.reloadRequired": "Rechargement nécessaire",
        "personal.loginTo": "Se connecter au compte Epherome",
        "personal.register": "S'inscrire",
        "personal.login": "Se connecter",
        "personal.openPersonalCenter": "Ouvrir le centre personnel",
        "personal.changeAvatar": "Changer d'avatar",
        "personal.logout": "Se déconnecter",
        "personal.notLoggedIn": "Non connecté",
        imageTooBig: "La taille de l'image doit être inférieure à 256 Ko.",
        notSelected: "Non sélectionné",
        "ext.added": "Ajouté",
        "ext.removed": "Supprimé",
        checkTokenAvailability: "Vérifier la disponibilité du jeton",
        "token.available.true": "Jeton disponible.",
        "token.available.false": "Jeton non disponible.",
        "profiles.dirUnavailable": "Répertoire non disponible.",
        "profiles.searchVersion": "Rechercher",
        serverControl: "Contrôle du serveur",
        "server.removing": "Suppression du serveur",
        marketplace: "Place de marché",
        newsTitleAmount: "Nombre de titres d'actualités",
        "newsTitleAmount.description":
        "Nombre de titres d'actualités affichés sur la page d'accueil. Valeurs acceptables : {0}.",
        disabled: "Désactivé",
        showRefreshButton: "Afficher le bouton de rafraîchissement",
        custom: "Personnalisé",
        "settings.allowNotificationDot": "Autoriser le point de notification",
        "news.description": "Les nouvelles sont fournies par Epherome. Elles incluent des contenus liés à Minecraft et à Epherome.",
        rememberWindowSize: "Mémoriser la taille de la fenêtre",
        "rememberWindowSize.description":
        "Si vous ne le cochez pas, la fenêtre démarrera avec la taille par défaut la prochaine fois.",
        backgroundPhoto: "Photo de fond",
        enableBackgroundPhoto: "Activer la photo de fond",
        functionBoardPlacement: "Position du tableau de fonctions",
        "placement.off": "Désactivé",
        "placement.top": "En haut",
        "placement.right": "À droite",
        filePath: "Chemin du fichier",
        "path.download": "Dossier de téléchargement",
        restoreDefault: "Restaurer les valeurs par défaut",
        "folder.description": "Dossier de destination de l'installation de Minecraft.",
        noNotifications: "Aucune notification",
        notifications: "Notifications",
        bugReport: "Signaler un bug",
        newServer: "Ajouter un serveur",
        status: "Statut",
        connecting: "Connexion en cours...",
        offline: "Hors ligne",
        online: "En ligne",
        serverIsOffline: "Le serveur est hors ligne.",
        noPlayersOnline: "Aucun joueur en ligne.",
        unableToShowTooManyPlayers: "Impossible d'afficher trop de joueurs.",
        noItems: "Aucun élément",
        standaloneProfiles: "Profils autonomes",
        hitokotoProvider: "Hitokoto",
        "hitokoto.description":
        "Affiche une phrase aléatoire fournie par {0} sur votre page d'accueil. (Contenu uniquement en chinois simplifié)",
        pleaseMoveTo: "Veuillez vous rendre sur {0} pour poser votre question.",
    },
};

export default frCH;