import { Language } from ".";

const ruRu: Language = {
  name: "ru-ru",
  nativeName: "Русский",
  definition: {
    hello: "Привет",
    home: "Главная",
    epherome: "Epherome",
    accounts: "Аккаунты",
    profiles: "Профили",
    settings: "Настройки",
    launch: "Запустить",
    launching: "Запуск",
    edit: "Изменить",
    news: "Новости",
    create: "Создать",
    cancel: "Отмена",
    remove: "Удалить",
    fine: "Хорошо",
    email: "Эл. почта",
    password: "Пароль",
    username: "Имя пользователя",
    authserver: "Сервер аутентификации",
    name: "Имя",
    directory: "Расположение",
    version: "Версия",
    general: "Общие",
    appearance: "Внешний вид",
    about: "О приложении",
    os: "ОС",
    language: "Язык",
    save: "Сохранить",
    warning: "Предупреждение",
    done: "Готово",
    add: "Добавить",
    tip: "Совет",
    help: "Справка",
    refresh: "Обновить",
    collapse: "Свернуть",
    expand: "Развернуть",
    useDefault: "<По умолчанию>",
    haveNot: "Ещё нет",
    export: "Экспорт",
    "account.mojang": "Mojang",
    "account.microsoft": "Microsoft",
    "account.authlib": "Authlib Injector",
    "account.offline": "Без пароля",
    "account.errCreating":
      "Неверная информация или не работает сервер аутентификации",
    "account.removing": "Удалить аккаунт",
    "account.notSelected": "Аккаунт не выбран",
    "account.wrongPassword": "Неверный пароль",
    "account.inputPassword": "Введите пароль",
    "account.msAccNoMinecraft":
      "У вас ещё нет Minecraft на аккаунте Microsoft.",
    "account.clickToLogin":
      "Нажмите «Создать», чтобы войти в свой аккаунт Microsoft.",
    "account.skin": "Скин",
    "account.skin.notSupportedExcludeMojangMs":
      "Поддерживается только просмотр скина Mojang или аккаунта Microsoft.",
    "profile.removing": "Удалить прфоиль",
    "profile.notSelected": "Профиль не выбран",
    "profile.openDirectory": "Обзор",
    "profile.usuallyDotMinecraftEtc":
      "Обычно «.minecraft» в Windows и «minecraft» в macOS и Linux.",
    "profile.maps": "Карты",
    "profile.resourcePacks": "Наборы текстур",
    "profile.resolution": "Разрешение",
    "profile.jvmArgs": "Аргументы JVM",
    "profile.noContent": "Нет контента",
    "profile.disable": "Отключить",
    "profile.enable": "Включить",
    "profile.import": "Импорт",
    "profile.gameDirIsolation": "Изоляция расположения игр",
    "profile.showEpherome": "Показать Epherome",
    "profile.gameDirIsolation.description":
      "Для каждой версии игры будет использоваться разное расположение.",
    "profile.showEpherome.description":
      "Отображение «Epherome» в левом нижнем углу на главной странице Minecraft.",
    "profile.install": "Установить",
    "profile.installing": "Установка",
    "profile.installForMinecraft": "Установка для Minecraft {0}",
    "profile.selectInstallContent": "Выберите что хотите установить.",
    "profile.installerAdaptToSomething": "{1} для Minecraft {0}",
    "profile.noInstallerAdaptToSomething": "Не найдено {1} для Minecraft {0}",
    "profile.canOnlyInstallOnVanilla":
      "«Установка» доступна только для ванильного Minecraft.",
    "profile.safeLog4j": "Безопасный Log4J",
    "profile.safeLog4j.description":
      "Включите «formatMsgNoLookups», чтобы предотвратить проблемы с Log4J.",
    "profile.exportModpack": "Экспорт модпака",
    "profile.gameOptionsPath": "Путь к параметрам игры",
    "profile.resourceType.resourcePack": "Набор текстур",
    "profile.resourceType.shaderPack": "Набор шейдеров",
    "settings.epheromePath": "Путь к Epherome",
    "settings.officialSite": "Официальный сайт",
    "settings.openSourceSoftware":
      "Программное обеспечение с открытым исходным кодом",
    "settings.downloadProvider": "Поставщик услуг скачивания",
    "settings.downloadProvider.official": "Официальный",
    "settings.downloadConcurrency": "Параллельное скачивание",
    "settings.hitokoto": "Hitokoto",
    "settings.theme": "Тема",
    "settings.theme.followOS": "Как в системе",
    "settings.titleBar": "Строка заголовка",
    "settings.titleBar.message":
      "Перезапустите Epherome, чтобы применить настройки строки заголовка.",
    "settings.devMode": "Режим разработчика",
    "settings.downloadProvider.description":
      "Если официальный источник работает медленно, вы можете попробовать заменить его.",
    "settings.downloadCurrency.description":
      "Количество файлов, которые можно скачать одновременно.",
    "settings.showNews": "Показывать новости",
    "settings.autoCheckUpdate": "Автопроверка обновлений",
    display: "Отображать",
    "java.executablePath": "Путь к исполняемому файлу Java",
    "java.manage": "Управление Java",
    "java.invalidPath": "Неверный путь",
    "java.duplicatePath": "Дублирующий путь",
    "java.detect": "Найти",
    "java.bitNumber": "{0}-бит",
    "java.default": "Java по умолчанию",
    "java.installJava": "Установить Java",
    "java.pleaseGoTo": "Если вы хотите загрузить этот JDK, перейдите по ссылке",
    "java.nickName": "Псевдоним JVM",
    download: "Скачать",
    downloading: "Скачивается",
    downloadingSomething: "Скачивается {0}",
    "download.profileName": "Имя профиля",
    "download.preparing": "Подготовка",
    "download.notSelected": "Версия не выбрана",
    "version.release": "Релиз",
    "version.snapshot": "Snapshot",
    "version.old": "Старая",
    "version.old_alpha": "Старая Alpha",
    "version.old_beta": "Старая Beta",
    processes: "Процессы",
    "processes.noMinecraft": "Нет процессов Minecraft",
    "processes.logExported": "Журнал экспортирован в\n{0}",
    "processes.terminate": "Завершить",
    "processes.terminateIrreversible":
      "Принудительное завершение процесса может привести к потере некоторых важных данных. Продолжить?",
    "processes.lookupLog": "Посмотреть журнал",
    "processes.exportLog": "Экспорт журнала",
    "processes.lookupProfile": "Посмотреть профиль",
    "processes.notSelected": "Процесс не выбран",
    extensions: "Расширения",
    epheromeUpdate: "Обновить Epherome",
    "epheromeUpdate.check": "Проверить обновления",
    "epheromeUpdate.available": "Доступна новая версия {0}.",
    "epheromeUpdate.availableMessage":
      "Перейдите на официальный сайт Epherome, для скачивания последней версии.",
    "epheromeUpdate.needNot": "Epherome уже последней версии.",
    "launching.noAccOrProSelected": "Не выбран аккаунт или профиль.",
    "launching.considerUsingJava17":
      "Для запуска Minecraft начиная с версии 1.18 требуется Java 17.",
    "launching.considerUsingJava16":
      "Для запуска Minecraft начиная с версии 1.17 требуется Java 16.",
    "launching.considerUsingJava8":
      "Для запуска Minecraft до версии 1.6 требуется Java 8.",
    "launching.javaNotFound": "Java не найдена",
    "launching.javaNotFoundMessage":
      "Неудаётся найти Java на вашем компьютере. Скачайте и установите её, затем выберите в настройках.",
    "launching.downloadingAsset": "Скачивание Assets",
    "launching.downloadingLib": "Скачивание Libraries",
    "launching.crashReport": "Minecraft рухнул!",
    "launching.crashReport.helper":
      "Для получения более подробной информации посмотрите страницу управление процессами.",
    "ext.apps": "Приложения",
    "theme.create": "Создать тему...",
    "theme.newTheme": "Новая тема",
    "theme.type": "Тип",
    "theme.light": "Светлая",
    "theme.dark": "Тёмная",
    "theme.background": "Фон",
    "theme.secondary": "Вторичный",
    "theme.divider": "Разделитель",
    "theme.contrast": "Контраст",
    "theme.primary": "Основной",
    "theme.shallow": "Поверхостный",
    "theme.card": "Карточка",
    "theme.danger": "Опасность",
    "task.manager": "Диспетчер задач",
    "task.noTasks": "Задачи не выполняются",
    "modpack.import": "Импорт модпака",
    "modpack.filePath": "Путь к файлу модпака (*.zip)",
    "modpack.unzipping": "Распаковка",
    "modpack.installingMinecraft": "Установка Minecraft",
    "modpack.installingModLoader": "Установка загрузчика модов",
    "modpack.info": "Информация о модпаке",
    "modpack.name": "Название модпака",
    "modpack.version": "Версия модпака",
    "modpack.author": "Автор модпака",
    "modpack.selectFiles": "Выберите файлы",
    "modpack.export": "Экспортировать",
    "modpack.exporting": "Экспорт",
    next: "След.",
    previous: "Пред.",
    search: "Поиск",
    internetNotAvailable:
      "Интернет для вас отличается, невозможно подключиться к Интернету.",
    errorOccurred: "Возникла ошибка",
    notSupportedYet: "К сожалению, эта функция пока не поддерживается.",
    confirmRemoving: "Уверены что хотите удалить? Операция необратима.",
    continueAnyway: "Продолжить в любом случае",
    moveToTrash: "Переместить в корзину",
    confirmMoveSomethingToTrash:
      "Уверены что хотите удалить {0} в корзину? Операция необратима.",
    exportedAt: "Экспорт в: ",
    versionOfSomething: "Версия {0}",
    doneMessage: "Эта задача была выполнена.",
    minimize: "Свернуть",
    quit: "Выход",
    confirmQuitting: "Выйти из Epherome?",
    removeFilesAsWell: "Удалить также файлы",
    unableToRefreshMsToken:
      "Не удалось обновить токен аккаунта Microsoft, повторите вход заново.",
    msLoginAgain: "Повторить вход",
    ephPersonalCenter: "Персональный центр",
    ephLogin: "Вход",
    "ext.installed": "Установлено",
    "ext.recommended": "Рекомендуется",
    "ext.all": "Все",
    "ext.noItems": "Элементов нет",
    "ext.remove": "Удалить из Epherome",
    "ext.add": "Добавить в Epherome",
    "ext.reloadRequired": "Требуется перезагрузка",
    "personal.loginTo": "Войти в Epherome",
    "personal.register": "Зарегестрироваться",
    "personal.login": "Войти",
    "personal.openPersonalCenter": "Открыть персональный центр",
    "personal.changeAvatar": "Изменить аватар",
    "personal.logout": "Выйти",
    "personal.notLoggedIn": "Вход в систему не произведён",
    imageTooBig: "Размер изображения не должен превышать 256 КБ.",
    notSelected: "Не выбрано",
    "ext.added": "Добавлено",
    "ext.removed": "Удалено",
    checkTokenAvailability: "Проверить наличие токена",
    "token.available.true": "Токен доступен.",
    "token.available.false": "Токен недоступен.",
    "profiles.dirUnavailable": "Расположение не доступно.",
    "profiles.searchVersion": "Поиск",
    serverControl: "Управление сервером",
    "server.removing": "Удалить сервер",
  },
};

export default ruRu;
