import { Language } from ".";

const enUs: Language = {
  name: "en-us",
  nativeName: "English",
  definition: {
    hello: "Hello",
    epherome: "Epherome",
    accounts: "Accounts",
    profiles: "Profiles",
    settings: "Settings",
    launch: "Launch",
    launching: "Launching",
    edit: "Edit",
    news: "News",
    create: "Create",
    cancel: "Cancel",
    remove: "Remove",
    fine: "Fine",
    email: "E-mail",
    password: "Password",
    username: "Username",
    authserver: "Authserver",
    name: "Name",
    directory: "Directory",
    version: "Version",
    general: "General",
    appearance: "Appearance",
    about: "About",
    os: "OS",
    language: "Language",
    save: "Save",
    warning: "Warning",
    done: "Done",
    add: "Add",
    "account.mojang": "Mojang",
    "account.microsoft": "Microsoft",
    "account.authlib": "Authlib Injector",
    "account.offline": "Offline",
    "account.errCreating":
      "The information is incorrect or the authentication server is down",
    "account.removing": "Remove Account",
    "account.notSelected": "No Account Selected",
    "account.wrongPassword": "Password Wrong",
    "account.inputPassword": "Please Input Password",
    "account.msAccNoMinecraft":
      "You don't have Minecraft in your Microsoft account yet.",
    "account.clickToLogin":
      "Click 'Create' to log in to your Microsoft account.",
    "profile.removing": "Remove Profile",
    "profile.notSelected": "No Profile Selected",
    "profile.openDirectory": "Open",
    "profile.usuallyDotMinecraftEtc":
      "Usually '.minecraft' on Windows and 'minecraft' on macOS and Linux.",
    "profile.maps": "Maps",
    "profile.resourcePacks": "Resourcepacks",
    "settings.configFilePath": "Config File Path",
    "settings.minecraftDownloadPath": "Minecraft Download Path",
    "settings.officialSite": "Official Site",
    "settings.openSourceSoftware": "Open Source Software",
    "settings.downloadProvider": "Download Provider",
    "settings.downloadProvider.notAvailable":
      "Sorry that download provider is not available now.",
    "settings.downloadProvider.official": "Official",
    "settings.hitokoto": "Hitokoto",
    "settings.hitokoto.description":
      "Display a random line of text provided by Epherome on your homepage.",
    "settings.theme": "Theme",
    "settings.theme.followOS": "Follow OS",
    "java.executablePath": "Java Executable Path",
    "java.manage": "Manage Java",
    "java.newPath": "New Path",
    "java.invalidPath": "Invalid Path",
    "java.duplicatePath": "Duplicate Path",
    "java.detect": "Detect",
    "java.bitNumber": "%s-Bit",
    download: "Download",
    downloading: "Downloading",
    downloadingSomething: "Downloading %s",
    "version.release": "Release",
    "version.snapshot": "Snapshot",
    "version.old": "Old",
    processes: "Processes",
    "processes.noMinecraft": "No Minecraft Processes",
    extensions: "Extensions",
    epheromeUpdate: "Epherome Update",
    "epheromeUpdate.check": "Check Update",
    "epheromeUpdate.available": "New version %s is available.",
    "epheromeUpdate.availableMessage":
      "Please go to Epherome official website to download the latest version.",
    "epheromeUpdate.needNot": "Epherome is the latest version.",
    "launching.noAccOrProSelected": "No account or profile selected.",
    "launching.continueAnyway": "Continue Anyway",
    "launching.considerUsingJava16":
      "Java 16 is required to launch Minecraft since 1.17.",
    "launching.considerUsingJava8":
      "Java 8 is required to launch Minecraft before 1.8.9.",
    "launching.javaNotFound": "Java Not Found",
    "launching.javaNotFoundMessage":
      "Java not found on your computer. Please install one and add it through settings.",
    "launching.downloadingAsset": "Downloading Assets",
    "launching.downloadingLib": "Downloading Libraries",
    internetNotAvailable:
      "The web is different for you, cannot connect to the Internet.",
    errorOccurred: "Error Occurred",
    notSupportedYet: "Sorry that this is not supported yet.",
    confirmRemoving:
      "Are you sure you want to remove it? The operation is irreversible.",
  },
};

export default enUs;
