import { Language } from ".";

const jaJp: Language = {
  name: "ja-jp",
  nativeName: "日本語",
  definition: {
    hello: "こんにちは！",
    epherome: "Epherome",
    accounts: "アカウント",
    profiles: "プロフィル",
    settings: "設定",
    launch: "起動",
    launching: "起動中",
    edit: "編集",
    news: "お知らせ",
    create: "作成",
    cancel: "取り消し",
    remove: "削除",
    fine: "はい",
    email: "Eメール",
    password: "パスワード",
    username: "ユーザー名",
    authserver: "認証サーバー",
    name: "名前",
    directory: "パス",
    version: "バージョン",
    general: "一般",
    appearance: "外観",
    about: "について",
    os: "システム",
    language: "言語",
    save: "セーブ",
    warning: "警告",
    done: "完了",
    add: "追加",
    tip: "チップ",
    help: "ヘルプ",
    refresh: "リフレッシュ",
    collapse: "片付け",
    expand: "展開する",
    useDefault: "<ディフォルト>",
    haveNot: "ありません",
    "account.mojang": "Mojang",
    "account.microsoft": "Microsoft",
    "account.authlib": "Authlib Injector",
    "account.offline": "オフライン",
    "account.errCreating":
      "情報が間違っているか、認証サーバーがダウンしています。",
    "account.removing": "アカウントを削除",
    "account.notSelected": "アカウントが選択されていません",
    "account.wrongPassword": "間違ったパスワード",
    "account.inputPassword": "パスワードを入力してください",
    "account.msAccNoMinecraft":
      "Microsoft アカウントには Minecraft がありません",
    "account.clickToLogin":
      "「作成」をクリックして、Microsoft アカウントにログインします。",
    "account.skin": "スキン",
    "profile.removing": "プロフィルを削除",
    "profile.notSelected": "プロフィルが選択だれていません",
    "profile.openDirectory": "パスを開けて",
    "profile.usuallyDotMinecraftEtc":
      "通常、Windows では「.minecraft」、macOS および Linux では「minecraft」です。",
    "profile.maps": "マップ",
    "profile.resourcePacks": "リソースパック",
    "profile.resolution": "解像度",
    "profile.jvmArgs": "JVM 引数",
    "profile.noContent": "内容がありません",
    "profile.disable": "無効にする",
    "profile.enable": "有効にする",
    "profile.import": "インポート",
    "profile.gameDirIsolation": "ゲームディレクトリの分離",
    "settings.configFilePath": "設定ファイルパス",
    "settings.minecraftDownloadPath": "Minecraft ダウンロードパス",
    "settings.officialSite": "公式サイト",
    "settings.openSourceSoftware": "オープンソースソフトウェア",
    "settings.downloadProvider": "ダウンロードソース",
    "settings.downloadProvider.official": "公式",
    "settings.downloadConcurrency": "ダウンロード並行数",
    "settings.hitokoto": "一言",
    "settings.hitokoto.description":
      "Epherome が提供するランダムなテキストをホームページに表示します。",
    "settings.theme": "テーマ",
    "settings.theme.followOS": "システムをフォロー",
    "java.executablePath": "Java パス",
    "java.manage": "Java を管理",
    "java.newPath": "新しいパス",
    "java.invalidPath": "間違ったパス",
    "java.duplicatePath": "重複するパス",
    "java.detect": "検出する",
    "java.bitNumber": "%s ビット",
    "java.default": "デフォルト Java",
    download: "ダウンロード",
    downloading: "ダウンロード中",
    downloadingSomething: "%s をダウンロード中",
    "download.profileName": "プロフィル名前",
    "download.preparing": "準備中",
    "download.notSelected": "バージョンが選択だれていません",
    "version.release": "リリース",
    "version.snapshot": "スナップショット",
    "version.old": "古い",
    "version.old_alpha": "古い Alpha",
    "version.old_beta": "古い Beta",
    processes: "プロセス",
    "processes.noMinecraft": "Minecraft プロセスはありません",
    "processes.logExported": "ログは\n%s\nにエクスポートされました。",
    "processes.terminate": "強制終了",
    "processes.terminateIrreversible":
      "プロセスを強制的に終了すると、いくつかの重要なデータが失われる可能性があります。続行しますか？",
    "processes.lookupLog": "ログを見る",
    "processes.exportLog": "ログをエクスポート",
    "processes.lookupProfile": "プロフィルを見る",
    "processes.notSelected": "プロセスが選択されていません",
    extensions: "拡張",
    epheromeUpdate: "Epherome 更新",
    "epheromeUpdate.check": "更新を確認する",
    "epheromeUpdate.available": "新しいバージョン %s が利用可能です。",
    "epheromeUpdate.availableMessage":
      "Epherome の公式ウェブサイトにアクセスして最新バージョンをダウンロードしてください。",
    "epheromeUpdate.needNot": "Epherome は最新バージョンです。",
    "launching.noAccOrProSelected":
      "アカウントまたはプロフィルを選択されていません",
    "launching.considerUsingJava16":
      "1.17 以降、Minecraft を起動するには Java 16 が必要です。",
    "launching.considerUsingJava8":
      "1.6 より前に Minecraft を起動するには Java 8 が必要です。",
    "launching.javaNotFound": "Java が見つかりません",
    "launching.javaNotFoundMessage":
      "コンピュータにJavaが見つかりません。 インストールして、設定で追加してください。",
    "launching.downloadingAsset": "リソースをダウンロードしています",
    "launching.downloadingLib": "ライブラリをダウンロードしています",
    internetNotAvailable:
      "Web はあなたにとって異なる、インターネットに接続できません。",
    errorOccurred: "エラーが発生しました",
    notSupportedYet: "すみません、これはさポードされていません。",
    confirmRemoving: "削除してもよろしいですか？操作は元に戻せません。",
    continueAnyway: "とにかく続け",
    moveToTrash: "ゴミ箱に移動",
    confirmMoveSomethingToTrash:
      "%s をゴミ箱に移動してもよろしいですか？操作は元に戻せません。",
  },
};

export default jaJp;
