export default {
  name: "简体中文",
  code: "zh-cn",
  messages: {
    counter: {
      increase: "增加",
      clicked: (count: number) => `你已经点击这个按钮 ${count} 次。`,
    },
    account: "账户",
    instance: "实例",
    remove: "移除",
    create: "创建",
    cancel: "取消",
    browse: "浏览",
    unsupported: "请拭目以待。",
    name: "名称",
    username: "用户名",
    email: "电子邮箱",
    password: "密码",
    unselected: "未选定",
    sidebar: {
      home: "首页",
      accounts: "账户",
      instances: "实例",
      counter: "计数器",
      settings: "设置",
    },
    home: {
      launch: "启动",
    },
    accounts: {
      empty: "还没有账户。",
      unopened: "在左侧打开一个账户或者创建新账户。",
      microsoft: "微软账户",
      authlib: "外置登录",
      offline: "离线登录",
      authserver: "验证服务器",
      type: "账户类型",
      removeConfirmation: (name: string) => `你真的想要移除账户 ${name} 吗？`,
      token: {
        validate: "检查令牌状态",
        available: "令牌可用",
        unavailable: "令牌不可用",
      },
    },
    instances: {
      empty: "还没有实例。",
      gameDir: "游戏文件夹",
      gameDirHelper:
        "通常是 Windows 上的 '.minecraft' 文件夹和 macOS 或 Linux 上的 'minecraft' 文件夹。",
      version: "版本",
      versionHelper: "游戏文件夹中的 'versions' 文件夹中的文件夹名。",
      unopened: "在左侧打开一个实例或者创建新实例。",
      removeConfirmation: (name: string) => `你真的想要移除实例 ${name} 吗？`,
    },
    settings: {
      general: "常规",
      appearance: "外观",
      download: "下载",
      about: "关于",
      noOptions: "还没有设置项。",
      displayLanguage: "显示语言",
      warning:
        "Nightly 版本极端不稳定。\n欢迎在 GitHub Issues 提出问题和建议。",
      tauriVersion: "Tauri 版本",
      dataDir: "数据文件夹",
      officialSite: "官方网站",
      githubHomepage: "GitHub 首页",
      oss: "开源软件",
    },
  },
};
